### PR TITLE
function from 2d-array to Forsyth Edwards notation

### PR DESCRIPTION
**Pull request by FilipKowalski**

### CODE REVIEW

**Comment by matthu2711** [comment]
- Looks good. Maybe differentiate pieces chars more than by just capitalisation, cause it could get confusing further down the line

**Review by liul4 — APPROVED** [review]
Looks good. Maybe add more comment in code to make it more understandable

**Comment by LiamHoogstad** [comment]
Looks good! As above maybe add more comments to make integration with other parts easier

**Comment by FilipKowalski** [comment]
> * Looks good. Maybe differentiate pieces chars more than by just capitalisation, cause it could get confusing further down the line

Forsyth-Edwards notation uses capitalisation to distinguish between black and white pieces so it's easier to build the string if the pieces are represented that way in the game state

**Pull request merged**
